export const SCENARIOS = [
    { headline: "BTC ВПАВ ДО $10k ЧЕРЕЗ ФЕЙКОВИЙ ТВІТ", move: "SHORT", roi: "+420%", msg: "Ти продав дно, але це виявилося не дно. Геній." },
    { headline: "SEC ЗАБОРОНИЛА DEFI (ЗНОВУ)", move: "SHORT", roi: "+69%", msg: "Гері Генслер плаче, ти рахуєш прибуток." },
    { headline: "LIQUID ЗАПУСТИВ ШІ-ПРОТОКОЛ", move: "LONG", roi: "+800%", msg: "Ти вклався в майбутнє, а не в мемкоіни." },
    { headline: "ІЛОН МАСК ЗАПОСТИВ СОБАКУ", move: "LONG", roi: "+1000%", msg: "DOGE летить на Марс, твій депозит теж." },
    { headline: "ETHEREUM Foundation ПРОДАВ 10k ETH", move: "SHORT", roi: "+150%", msg: "Віталік купив новий острів, а ти заробив на піцу." },
    { headline: "SBF ВТІК З В'ЯЗНИЦІ", move: "SHORT", roi: "+300%", msg: "FTX 2.0 не буде. Ринок в паніці, ти в плюсі." },
    { headline: "КИТАЙ ДОЗВОЛИВ КРИПТУ", move: "LONG", roi: "+500%", msg: "Азійський памп нещадний. Зелені свічки всюди." },
    { headline: "USDT ВТРАТИВ ПРИВ'ЯЗКУ (0.98$)", move: "SHORT", roi: "+200%", msg: "Стейблкоіни не такі вже й стабільні." },
    { headline: "MICROSTRATEGY КУПИЛА ЩЕ БІТКОЇНІВ", move: "LONG", roi: "+50%", msg: "Майкл Сейлор твій найкращий друг." },
    { headline: "НОВИЙ ЕКСПЛОЙТ В SOLANA", move: "SHORT", roi: "+120%", msg: "Блокчейн знову вимкнули. Класика." },
    { headline: "BLACKROCK ПОДАВ ЗАЯВКУ НА XRP ETF", move: "LONG", roi: "+333%", msg: "Інституціонали заходять. Ти встиг першим." },
    { headline: "HACKER DRAINED CURVE POOLS", move: "SHORT", roi: "+666%", msg: "DeFi мертвий (на 5 хвилин). Ти заробив на крові." },
    { headline: "PEPE ОБІГНАВ SHIBA INU", move: "LONG", roi: "+420%", msg: "Жаба з'їла собаку. Твій гаманець вдячний." },
    { headline: "BINANCE ОТРИМАЛА ЛІЦЕНЗІЮ В США", move: "LONG", roi: "+100%", msg: "CZ повертається? Ринок вірить." },
    { headline: "FED ЗНИЗИВ СТАВКУ ДО 0%", move: "LONG", roi: "+999%", msg: "Дрокарський верстат робить бррррр." },
    { headline: "TETHER НЕ ПРОЙШОВ АУДИТ", move: "SHORT", roi: "+300%", msg: "FUD вічний, як і твій прибуток." },
    { headline: "БІТКОЇН ETF ВІДХИЛЕНО", move: "SHORT", roi: "+250%", msg: "Гарі знову все зіпсував. Шорт спрацював." },
    { headline: "VITALIK ВИТРАТИВ ETH НА БЛАГОДІЙНІСТЬ", move: "SHORT", roi: "+40%", msg: "Ринок впав, але карма чиста." },
    { headline: "TRON ЗВИНУВАТИЛИ В ВІДМИВАННІ", move: "SHORT", roi: "+80%", msg: "Джастін Сан знову в новинах." },
    { headline: "BITCOIN HALVING ВІДБУВСЯ", move: "LONG", roi: "+200%", msg: "Дефіцит працює. Ціна летить вгору." },
    { headline: "ГАЗ В ETHEREUM ВПАВ ДО 1 GWEI", move: "LONG", roi: "+50%", msg: "Можна нарешті користуватися мережею." },
    { headline: "LUNA 3.0 ЗАПУЩЕНА", move: "SHORT", roi: "+1000%", msg: "Ти не повівся на скам втретє. Молодець." },
    { headline: "COINBASE КУПИЛА ROBINHOOD", move: "LONG", roi: "+150%", msg: "Централізація? Можливо. Прибуток? Точно." },
    { headline: "NFT ПОВЕРНУЛИСЯ В МОДУ", move: "LONG", roi: "+300%", msg: "JPEG знову коштують мільйони." },
    { headline: "METAMASK ВИПУСТИВ ТОКЕН", move: "LONG", roi: "+5000%", msg: "Аірдроп століття. Ти багатий." },
    { headline: "LEDGER ЗЛИВ СІД-ФРАЗИ", move: "SHORT", roi: "+200%", msg: "Довіри немає, зате є профіт на шорті." },
    { headline: "AVALANCHE ПАРТНЕРИТЬСЯ З AMAZON", move: "LONG", roi: "+180%", msg: "Корпорації люблять сабнети." },
    { headline: "ПОЛІЦІЯ ЗААРЕШТУВАЛА РОЗРОБНИКІВ TORNADO", move: "SHORT", roi: "+90%", msg: "Приватність під атакою. Ринок реагує падінням." },
    { headline: "САТТОШІ НАКАМОТО ПРОКИНУВСЯ", move: "SHORT", roi: "+10000%", msg: "Гаманець 2009 року активний. Паніка тотальна." },
    { headline: "APPLE ДОДАЛА КРИПТО-ГАМАНЕЦЬ", move: "LONG", roi: "+300%", msg: "Мас-адопшн вже тут." },
    { headline: "КРАХ БАНКУ SILVERGATE", move: "SHORT", roi: "+150%", msg: "Крипто-банкінг помер. Хай живе P2P." },
    { headline: "ARBITRUM РОЗДАВ АІРДРОП", move: "LONG", roi: "+400%", msg: "Безкоштовні гроші існують." },
    { headline: "SOLANA ЗАПУСТИЛА ТЕЛЕФОН SAGA 2", move: "LONG", roi: "+70%", msg: "Бонк в подарунок. Ціна росте." },
    { headline: "SEC ПРОГРАЛА СУД ПРОТИ GRAYSCLAE", move: "LONG", roi: "+120%", msg: "Закон на нашому боці... поки що." },
    { headline: "ЕЛ САЛЬВАДОР КУПИВ ЩЕ 1 BTC", move: "LONG", roi: "+10%", msg: "Президент-біктоїнер тримає стрій." },
    { headline: "КВАНТОВИЙ КОМП'ЮТЕР ЗЛАМАВ SHA-256", move: "SHORT", roi: "+∞%", msg: "Кінець гри. Ти зашортив кінець світу." },
    { headline: "ВІТАЛІК БУТЕРІН ОДРУЖИВСЯ", move: "LONG", roi: "+69%", msg: "Всі купують ETH як весільний подарунок." },
    { headline: "МЕМКОЇН ЗЛЕТІВ НА 10000%", move: "LONG", roi: "+1000%", msg: "Ти вгадав з тікером $PEPE2.0." },
    { headline: "БІРЖА FTX ПОВЕРТАЄ КОШТИ", move: "LONG", roi: "+50%", msg: "Диво сталося." },
    { headline: "ЗАБОРОНА МАЙНІНГУ В США", move: "SHORT", roi: "+100%", msg: "Хешрейт падає, ціна за ним." },
    { headline: "MICROSOFT ІНТЕГРУЄ WALLET", move: "LONG", roi: "+200%", msg: "Windows тепер майнить." },
    { headline: "LINK ПАРТНЕРИТЬСЯ З SWIFT", move: "LONG", roi: "+150%", msg: "Оракули правлять світом." },
    { headline: "USDC ЗАБЛОКУВАВ ГАМАНЦІ", move: "SHORT", roi: "+40%", msg: "Цензура. Люди тікають в DAI." },
    { headline: "DAI ВТРАТИВ ПРИВ'ЯЗКУ", move: "SHORT", roi: "+80%", msg: "Алгоритми зламалися." },
    { headline: "SUI ОБВАЛИВСЯ ПІСЛЯ АНЛОКУ", move: "SHORT", roi: "+110%", msg: "Токеноміка VC ніколи не підводить (їх)." },
    { headline: "APTOS ЗУПИНИВСЯ НА 5 ГОДИН", move: "SHORT", roi: "+60%", msg: "Move мова швидка, але не надійна?" },
    { headline: "BASE ОБІГНАВ ARBITRUM", move: "LONG", roi: "+90%", msg: "Coinbase будує екосистему." },
    { headline: "FRIEND.TECH ЗЛАМАЛИ", move: "SHORT", roi: "+200%", msg: "Соціальні ключі нічого не варті." },
    { headline: "BLAST ЗАПУСТИВ МАЙНЕТ", move: "LONG", roi: "+300%", msg: "Понці чи геніальність? Поки що лонг." },
    { headline: "EIGENLAYER ЗАПУСТИВСЯ", move: "LONG", roi: "+400%", msg: "Рестейкінг - новий наратив." },
    { headline: "CELESTIA ОНОВИЛА ATH", move: "LONG", roi: "+250%", msg: "Модульність перемагає." },
    { headline: "JUPITER РОЗДАВ АІРДРОП", move: "LONG", roi: "+500%", msg: "Solana DeFi годує." },
    { headline: "WORMHOLE ХАКНУЛИ (ЗНОВУ)", move: "SHORT", roi: "+300%", msg: "Мости - це зло." },
    { headline: "LAYERZERO ТОКЕН ВИЙШОВ", move: "SHORT", roi: "+50%", msg: "Продали на новинах." },
    { headline: "ZK-SYNC НЕ РОЗДАВ ТОКЕНИ", move: "SHORT", roi: "+20%", msg: "Спільнота лютує." },
    { headline: "STARKNET ЗНИЗИВ КОМІСІЇ", move: "LONG", roi: "+40%", msg: "ZK-ролапи нарешті дешеві." },
    { headline: "OPTIMISM ВИДІЛИВ ГРАНТИ", move: "LONG", roi: "+60%", msg: "Екосистема розквітає." },
    { headline: "POLYGON ЗМІНИВ ТІКЕР НА POL", move: "LONG", roi: "+30%", msg: "Ребрендинг вдався." },
    { headline: "CARDANO ЗАПУСТИЛА СМАРТ-КОНТРАКТИ", move: "SHORT", roi: "+10%", msg: "Вже запізно. Ніхто не користується." },
    { headline: "RIPPLE ВИГРАВ ЩЕ ОДИН СУД", move: "LONG", roi: "+80%", msg: "XRP армія святкує." },
    { headline: "TON ІНТЕГРУВАЛИ В TELEGRAM", move: "LONG", roi: "+600%", msg: "Мільярд користувачів. Це серйозно." },
    { headline: "NOTCOIN ЛІСТИНГ НА BINANCE", move: "SHORT", roi: "+300%", msg: "Натиснув 'продати' вчасно." },
    { headline: "HAMSTER KOMBAT SCAM", move: "SHORT", roi: "+∞%", msg: "Хом'яки поголені." },
    { headline: "DOGWIFHAT НА СФЕРІ В ЛАС-ВЕГАСІ", move: "LONG", roi: "+1000%", msg: "Собака в шляпі - символ буллрану." },
    { headline: "BOME ЗРОБИВ 100X ЗА ДЕНЬ", move: "LONG", roi: "+10000%", msg: "Солана меми - це казино." },
    { headline: "SLERF СПАЛИВ ЛІКВІДНІСТЬ", move: "LONG", roi: "+500%", msg: "Помилка розробника створила легенду." },
    { headline: "RUNES ЗАБИЛИ МЕРЕЖУ БІТКОЇНА", move: "SHORT", roi: "+40%", msg: "Комісії $100. Юзери плачуть." },
    { headline: "ORDINALS ПРОДАЛИСЯ ЗА $1М", move: "LONG", roi: "+200%", msg: "Картинки на біткоїні назавжди." },
    { headline: "BRC-20 ПОМЕРЛИ", move: "SHORT", roi: "+90%", msg: "Хайп пройшов." },
    { headline: "MERLIN CHAIN ВЗЛАМАЛИ", move: "SHORT", roi: "+150%", msg: "L2 на біткоїні - ризикована справа." },
    { headline: "BABYLON ЗАПУСТИВ СТЕЙКІНГ BTC", move: "LONG", roi: "+120%", msg: "Біткоїн починає приносити дохід." },
    { headline: "PENDLE TVL ДОСЯГ $5B", move: "LONG", roi: "+200%", msg: "Торгівля дохідністю - це для профі." },
    { headline: "ETHENA ПРОПОНУЄ 50% APY", move: "LONG", roi: "+100%", msg: "USDe виглядає як UST? Поки що ні." },
    { headline: "RENZO DEPEG", move: "SHORT", roi: "+300%", msg: "ezETH втратив прив'язку. Паніка." },
    { headline: "PUFFER FINANCE АІРДРОП", move: "LONG", roi: "+150%", msg: "Восьминіг роздав щедро." },
    { headline: "ZORA КУПИЛА OPENSEA", move: "LONG", roi: "+80%", msg: "NFT маркетплейси консолідуються." },
    { headline: "LENS PROTOCOL ТОКЕН", move: "LONG", roi: "+220%", msg: "SocialFi нарешті працює." },
    { headline: "FARCASTER ОЦІНКА $1B", move: "LONG", roi: "+300%", msg: "Децентралізований твіттер переміг." },
    { headline: "DEGEN CHAIN ОБВАЛИВСЯ", move: "SHORT", roi: "+400%", msg: "L3 це занадто складно." },
    { headline: "AAVE V4 АНОНСОВАНО", move: "LONG", roi: "+50%", msg: "Дідусь DeFi ще покаже." },
    { headline: "UNISWAP ОТРИМАВ ПОВІСТКУ ВІД SEC", move: "SHORT", roi: "+30%", msg: "Хейден Адамс готовий до бою." },
    { headline: "COMP PUMP & DUMP", move: "SHORT", roi: "+120%", msg: "Класична маніпуляція китів." },
    { headline: "MKR СПАЛЮЄ ТОКЕНИ", move: "LONG", roi: "+70%", msg: "DAI забезпечений RWA." },
    { headline: "RWA ТРЕНД: BLACKROCK КУПУЄ ONDO", move: "LONG", roi: "+400%", msg: "Токенізація активів - це майбутнє." },
    { headline: "GOLDMAN SACHS ЗАПУСКАЄ КРИПТО-ДЕСК", move: "LONG", roi: "+100%", msg: "Банкіри тут. Памп it." },
    { headline: "JP MORGAN: БІТКОЇН ЦЕ ШАХРАЙСТВО", move: "SHORT", roi: "+10%", msg: "Джеймі Даймон скуповує дно." },
    { headline: "TORNADO CASH РОЗРОБНИКА ЗАСУДИЛИ", move: "SHORT", roi: "+5%", msg: "Сумний день для шифропанків." },
    { headline: "MONERO ВИДАЛИЛИ З БІРЖ", move: "SHORT", roi: "+60%", msg: "Приватність більше не в пошані." },
    { headline: "ZCASH ПЕРЕЙШОВ НА POS", move: "LONG", roi: "+30%", msg: "Екологічна приватність." },
    { headline: "IRONFISH РЕКТ", move: "SHORT", roi: "+90%", msg: "Ще один майнінг коін вмер." },
    { headline: "KASPA ЗРОБИЛА 100X", move: "LONG", roi: "+500%", msg: "POW живий! DAG технологія." },
    { headline: "ALEPHIUM НОВИЙ ATH", move: "LONG", roi: "+200%", msg: "Шардінг працює." },
    { headline: "NVIDIA ОБІГНАЛА BITCOIN ПО КАПІ", move: "SHORT", roi: "+50%", msg: "ШІ бульбашка більша за крипто." },
    { headline: "RENDER ПЕРЕЙШОВ НА SOLANA", move: "LONG", roi: "+150%", msg: "GPU рендерінг дешевший." },
    { headline: "IO.NET СКАНДАЛ З GPU", move: "SHORT", roi: "+200%", msg: "Фейкові чіпи. Ціна вниз." },
    { headline: "AKASH МЕРЕЖА ПЕРЕВАНТАЖЕНА", move: "SHORT", roi: "+20%", msg: "Попит на хмари шалений." },
    { headline: "NEAR ПАРТНЕРСТВО З ALIBABA", move: "LONG", roi: "+80%", msg: "Шардінг + Китай = Успіх." },
    { headline: "POLKADOT 2.0 ЗАПУЩЕНО", move: "LONG", roi: "+40%", msg: "Гейвін Вуд все ще кодить." },
    { headline: "KUSAMA ПОМЕРЛА", move: "SHORT", roi: "+95%", msg: "Канарка в шахті здохла." }
];
