export const SCENARIOS = [
    // --- ORIGINAL 58 ---
    { headline: "ELON TWEETED A DOG PIC", move: "LONG", roi: "+420%", msg: "The Dogefather has spoken. Your bags are mooning." },
    { headline: "SEC SUES DEFI PROTOCOL", move: "SHORT", roi: "+69%", msg: "Gary is angry again. Prices tank, but your short prints." },
    { headline: "DEV RUGGED THE LIQUIDITY", move: "SHORT", roi: "+900%", msg: "Classic move. You saw it coming and shorted the top." },
    { headline: "BLACKROCK ETF APPROVED", move: "LONG", roi: "+1000%", msg: "Institutional money is here. We are so back." },
    { headline: "EXCHANGE HALTS WITHDRAWALS", move: "SHORT", roi: "+100%", msg: "Not your keys, not your coins. Panic sellers filled your bags." },
    { headline: "INFLUENCER SHILLS 'GEM'", move: "SHORT", roi: "+50%", msg: "Exit liquidity secured. You dumped on them." },
    { headline: "FED PRINTS $1 TRILLION", move: "LONG", roi: "+200%", msg: "Money printer go BRRR. Assets fly up." },
    { headline: "SMART CONTRACT HACKED", move: "SHORT", roi: "+300%", msg: "Code is law? More like Code is Flawed." },
    { headline: "CHINA BANS BITCOIN (AGAIN)", move: "LONG", roi: "+150%", msg: "FUD is bullish. You bought the dip." },
    { headline: "VITALIK CLAPS HANDS", move: "LONG", roi: "+42%", msg: "The creator is happy. Gas fees drop, price goes up." },
    { headline: "STABLECOIN DE-PEGS TO $0.90", move: "LONG", roi: "+500%", msg: "You bought the fear. It re-pegged. Easy arbitrage." },
    { headline: "MEMECOIN LISTED ON BINANCE", move: "SHORT", roi: "+80%", msg: "Buy the rumor, sell the news. It crashed instantly." },
    { headline: "SBF ESCAPES PRISON", move: "SHORT", roi: "+666%", msg: "FTX 2.0 isn't happening. Market panic-dumps." },
    { headline: "USDT AUDIT FAILED", move: "SHORT", roi: "+99%", msg: "Tether truthers were right (for 5 mins)." },
    { headline: "NEW L2 AIRDROP ANNOUNCED", move: "LONG", roi: "+300%", msg: "Free money glitch. Farmers are eating good." },
    { headline: "NFT FLOOR PRICE CRASHES", move: "SHORT", roi: "+75%", msg: "JPEGs are illiquid. You shorted the collection." },
    { headline: "YOUTUBER MAKES 'SORRY' VIDEO", move: "SHORT", roi: "+120%", msg: "The scam unravels. You profited from the tears." },
    { headline: "MICHAEL SAYLOR BUYS MORE", move: "LONG", roi: "+10%", msg: "God candle incoming. There is no second best." },
    { headline: "SOLANA NETWORK RESTART", move: "SHORT", roi: "+40%", msg: "The blockchain is 'offline/online'. You hedged correctly." },
    { headline: "JIM CRAMER SAYS 'SELL'", move: "LONG", roi: "+888%", msg: "Inverse Cramer never fails. Historic pump." },
    { headline: "QUANTUM COMPUTER CRACKS SHA-256", move: "SHORT", roi: "+∞%", msg: "Game over. You shorted the apocalypse." },
    { headline: "A.I. TRADING BOT GOES ROGUE", move: "SHORT", roi: "+200%", msg: "SkyNet dumped the market." },
    { headline: "WIFE CHANGING MONEY", move: "LONG", roi: "+1000%", msg: "You bought a coin with a cat on it. It worked." },
    { headline: "DISCORD MOD DRAINS WALLET", move: "SHORT", roi: "+50%", msg: "Never click the link. You survived." },
    { headline: "GAS FEES HIT 5000 GWEI", move: "SHORT", roi: "+20%", msg: "Network unusable. Retail can't buy." },
    { headline: "ANANAS FUND DONATES 5000 BTC", move: "LONG", roi: "+30%", msg: "Whales are feeling generous." },
    { headline: "SATOSHI WALLET ACTIVATES", move: "SHORT", roi: "+5000%", msg: "The ancient one awakes. Terror in the streets." },
    { headline: "INTERNET SHUTDOWN", move: "SHORT", roi: "+100%", msg: "Can't trade if you can't connect." },
    { headline: "ALIENS BUY BITCOIN", move: "LONG", roi: "+9999%", msg: "Intergalactic adoption confirms the bull run." },
    { headline: "TAX SEASON STARTS", move: "SHORT", roi: "+15%", msg: "Everyone selling to pay Uncle Sam." },
    { headline: "ETHEREUM GOES PROOF-OF-STAKE", move: "LONG", roi: "+5%", msg: "Miners are mad, investors are glad." },
    { headline: "COINBASE SUPER BOWL AD", move: "SHORT", roi: "+40%", msg: "Top signal indicator. You sold." },
    { headline: "DO KWON FOUND ON MOON", move: "LONG", roi: "+100%", msg: "LUNA 3.0 pumps on the news." },
    { headline: "SEC APPROVES ETH ETF", move: "LONG", roi: "+250%", msg: "The flippening gets closer." },
    { headline: "NORTH KOREA HACKS BRIDGE", move: "SHORT", roi: "+150%", msg: "Lazarus Group strikes again." },
    { headline: "REDDIT API CHANGES", move: "SHORT", roi: "+10%", msg: "Moon farmers are on strike." },
    { headline: "NFT SOLD FOR $69 MILLION", move: "LONG", roi: "+500%", msg: "Art bubble is back." },
    { headline: "METAVERSE LAND SALE", move: "SHORT", roi: "+90%", msg: "Digital grass is useless. You flattened it." },
    { headline: "WEB3 PHONE RELEASED", move: "LONG", roi: "+60%", msg: "Airdrops included. Physical utility." },
    { headline: "BINANCE CEO RESIGNS", move: "SHORT", roi: "+44%", msg: "Funds are SAFU, but the price isn't." },
    { headline: "TWITTER REBRANDS TO X", move: "LONG", roi: "+69%", msg: "DOGE payments rumored. Speculation runs wild." },
    { headline: "GAMESTOP NFT MARKETPLACE", move: "SHORT", roi: "+80%", msg: "Too little, too late. Short squeeze failed." },
    { headline: "AMAZON ACCEPTS CRYPTO", move: "LONG", roi: "+300%", msg: "Jeff Bezos pumps your bags." },
    { headline: "LINK MARINES ASSEMBLE", move: "LONG", roi: "+100%", msg: "The oracle monopoly continues." },
    { headline: "LEDGER RECOVERS SEED", move: "SHORT", roi: "+200%", msg: "Trust broken. Hardware wallets tossed." },
    { headline: "BITCONNECT 2.0 LAUNCH", move: "SHORT", roi: "+1000%", msg: "Hey hey hey! No no no." },
    { headline: "PEPE FLIPS SHIBA", move: "LONG", roi: "+420%", msg: "The frog creates a new paradigm." },
    { headline: "GOLDMAN SACHS SHORT", move: "LONG", roi: "+50%", msg: "Bankers are wrong. Again." },
    { headline: "CRYPTO BAN IN INDIA", move: "SHORT", roi: "+30%", msg: "Another ban? Another dip to buy later." },
    { headline: "ETHEREUM KILLER LAUNCHED", move: "SHORT", roi: "+95%", msg: "It died in 2 months. Expected." },
    { headline: "LOGAN PAUL PROJECT", move: "SHORT", roi: "+100%", msg: "Never trust a YouTuber. Refund unclear." },
    { headline: "APPLE DELISTS METAMASK", move: "SHORT", roi: "+40%", msg: "Walled garden strikes back." },
    { headline: "MICROSTRATEGY MARGIN CALL", move: "SHORT", roi: "+200%", msg: "Staylor got liquidated? No way." },
    { headline: "BTC DOMINANCE HITS 70%", move: "SHORT", roi: "+20%", msg: "Altcoins are bleeding out." },
    { headline: "ALTSEASON HAS BEGUN", move: "LONG", roi: "+1000%", msg: "Everything is going up. Even the trash." },
    { headline: "HACKER RETURNS FUNDS", move: "LONG", roi: "+50%", msg: "White hat saviour? Or just scared?" },
    { headline: "FED PIVOT CONFIRMED", move: "LONG", roi: "+400%", msg: "Rates are cut. Risk-on assets explode." },

    // --- NEW SCENARIOS (92 more to reach 150) ---
    { headline: "TRUMP LAUNCHES MEMECOIN", move: "LONG", roi: "+6900%", msg: "Politics and crypto collide. MAGA pumps." },
    { headline: "CELSIUS REFUNDS DEPOSITORS", move: "LONG", roi: "+80%", msg: "Miracles do happen. Confidence restored." },
    { headline: "BINANCE GETS US LICENSE", move: "LONG", roi: "+150%", msg: "The biggest exchange goes legit." },
    { headline: "PANCAKESWAP V4 LAUNCH", move: "LONG", roi: "+45%", msg: "BSC degens are eating good today." },
    { headline: "VC UNLOCK DUMPS MARKET", move: "SHORT", roi: "+110%", msg: "Tokenomics strikes again. You called it." },
    { headline: "TELEGRAM BOT SCAM ALERT", move: "SHORT", roi: "+60%", msg: "Another day, another drainer." },
    { headline: "WHALE SELLS $500M BTC", move: "SHORT", roi: "+70%", msg: "The sell wall was real. RIP bulls." },
    { headline: "AIRDROP HUNTERS EXPOSED", move: "SHORT", roi: "+25%", msg: "Sybil detection activated. Farmers rekt." },
    { headline: "NEW PONZI YIELDS 1000% APY", move: "SHORT", roi: "+500%", msg: "If it's too good to be true... it is." },
    { headline: "GIGABRAIN TRADER REVEALED", move: "LONG", roi: "+200%", msg: "Copy trading the alpha. It worked." },
    { headline: "BITCOIN PIZZA DAY PUMP", move: "LONG", roi: "+22%", msg: "10,000 BTC for pizza? Never forget." },
    { headline: "WBTC COLLATERAL CONCERNS", move: "SHORT", roi: "+35%", msg: "Wrapped assets under scrutiny." },
    { headline: "CBDC PILOT LAUNCHED", move: "SHORT", roi: "+15%", msg: "Digital dollar? Crypto dumps on fear." },
    { headline: "DEFI SUMMER 2.0", move: "LONG", roi: "+800%", msg: "Yield farming returns. APYs are back." },
    { headline: "VITALIK DUMPS MEMECOINS", move: "SHORT", roi: "+300%", msg: "Dev sold before you could." },
    { headline: "ORDINALS CLOG BITCOIN", move: "SHORT", roi: "+40%", msg: "Inscriptions fill blocks. Fees moon." },
    { headline: "SOLANA PHONE AIRDROP", move: "LONG", roi: "+2000%", msg: "Saga holders get free BONK." },
    { headline: "UNISWAP FEE SWITCH ON", move: "LONG", roi: "+120%", msg: "Protocol revenue flows to holders." },
    { headline: "POLYMARKET PREDICTION WRONG", move: "LONG", roi: "+50%", msg: "The crowd was wrong. You weren't." },
    { headline: "FLASH CRASH -20%", move: "LONG", roi: "+400%", msg: "You bought the bottom. Perfect entry." },
    { headline: "GRAYSCALE UNLOCKS GBTC", move: "SHORT", roi: "+30%", msg: "Premium discount causes selling." },
    { headline: "CELEBRITY LAUNCHES NFT", move: "SHORT", roi: "+85%", msg: "Another celebrity cash grab. Avoided." },
    { headline: "MULTICHAIN BRIDGE FAILS", move: "SHORT", roi: "+250%", msg: "Cross-chain risk is real." },
    { headline: "COINBASE STOCK SURGES", move: "LONG", roi: "+160%", msg: "Crypto stonks are back." },
    { headline: "ZKSYNC TOKEN LAUNCHES", move: "SHORT", roi: "+45%", msg: "Sold on listing. Classic move." },
    { headline: "BLUR SEASON 2 ENDING", move: "LONG", roi: "+35%", msg: "Point farmers liquidate NFTs." },
    { headline: "EIGENLAYER RESTAKING BOOM", move: "LONG", roi: "+180%", msg: "ETH staking on steroids." },
    { headline: "PENDLE YIELDS MAX OUT", move: "LONG", roi: "+90%", msg: "Fixed yield never looked better." },
    { headline: "LIDO DOMINANCE CONCERNS", move: "SHORT", roi: "+20%", msg: "Centralization FUD hits stETH." },
    { headline: "JITO AIRDROP ANNOUNCED", move: "LONG", roi: "+600%", msg: "Solana MEV protocol pays out." },
    { headline: "PYTH ORACLE LAUNCHES", move: "LONG", roi: "+75%", msg: "Real-time data on Solana." },
    { headline: "FRIEND TECH RETURNS", move: "SHORT", roi: "+150%", msg: "Social tokens pump and dump." },
    { headline: "INSCRIPTION META ENDS", move: "SHORT", roi: "+55%", msg: "BRC-20 hype dies down." },
    { headline: "FRAX V3 LAUNCH", move: "LONG", roi: "+40%", msg: "Algorithmic stablecoin improved." },
    { headline: "BLAST POINTS LAUNCH", move: "LONG", roi: "+250%", msg: "Yield casino opens." },
    { headline: "JUPITER PERPS LIVE", move: "LONG", roi: "+95%", msg: "Solana gets leverage trading." },
    { headline: "MARINADE STAKING BOOM", move: "LONG", roi: "+45%", msg: "mSOL adoption accelerates." },
    { headline: "PHANTOM WALLET UPDATE", move: "LONG", roi: "+15%", msg: "UX improvement bullish." },
    { headline: "MAGIC EDEN MULTICHAIN", move: "LONG", roi: "+35%", msg: "NFT liquidity spreads." },
    { headline: "TENSOR AIRDROP SEASON", move: "LONG", roi: "+420%", msg: "NFT traders rewarded." },
    { headline: "DRIFT PROTOCOL TVL SPIKES", move: "LONG", roi: "+80%", msg: "Solana perps gaining traction." },
    { headline: "KAMINO LAUNCH", move: "LONG", roi: "+110%", msg: "Concentrated liquidity on Solana." },
    { headline: "MARGINFI POINTS META", move: "LONG", roi: "+200%", msg: "Lending protocol farms hot." },
    { headline: "WORMHOLE AIRDROP", move: "LONG", roi: "+350%", msg: "Bridge users get paid." },
    { headline: "LAYERZERO SYBIL HUNT", move: "SHORT", roi: "+65%", msg: "Airdrop farmers exposed." },
    { headline: "BASE TVL SURGES", move: "LONG", roi: "+130%", msg: "Coinbase L2 gains momentum." },
    { headline: "ARBITRUM STIMULUS", move: "LONG", roi: "+55%", msg: "ARB grants flow to builders." },
    { headline: "OPTIMISM SUPERCHAIN", move: "LONG", roi: "+85%", msg: "OP Stack adoption grows." },
    { headline: "MANTA PACIFIC LAUNCH", move: "LONG", roi: "+190%", msg: "ZK privacy L2 goes live." },
    { headline: "SCROLL MAINNET", move: "LONG", roi: "+70%", msg: "zkEVM competition heats up." },
    { headline: "LINEA TOKEN SOON", move: "LONG", roi: "+145%", msg: "ConsenSys L2 hints airdrop." },
    { headline: "TAIKO TESTNET ENDS", move: "LONG", roi: "+100%", msg: "Mainnet imminent. Farmers ready." },
    { headline: "MODE NETWORK LAUNCH", move: "LONG", roi: "+220%", msg: "OP Stack chain with yield." },
    { headline: "METIS DECENTRALIZES", move: "LONG", roi: "+40%", msg: "L2 governance improves." },
    { headline: "MANTLE TVL GROWS", move: "LONG", roi: "+65%", msg: "BitDAO's L2 gains apps." },
    { headline: "POLYGON CDK ADOPTION", move: "LONG", roi: "+50%", msg: "Chains using ZK stack." },
    { headline: "AVAX SUBNET BOOM", move: "LONG", roi: "+75%", msg: "Gaming chains multiply." },
    { headline: "NEAR SHARDING UPGRADE", move: "LONG", roi: "+35%", msg: "Nightshade 2.0 launches." },
    { headline: "SUI TVL MILESTONE", move: "LONG", roi: "+80%", msg: "Move language gains adoption." },
    { headline: "APTOS DEX VOLUME SPIKES", move: "LONG", roi: "+55%", msg: "Move VM trading heats up." },
    { headline: "SEI V2 PARALLELIZATION", move: "LONG", roi: "+95%", msg: "Fastest L1 gets faster." },
    { headline: "INJECTIVE BURNS TOKENS", move: "LONG", roi: "+120%", msg: "Deflationary tokenomics work." },
    { headline: "CELESTIA DA COSTS DROP", move: "LONG", roi: "+25%", msg: "Modular blockchain thesis validated." },
    { headline: "TIA STAKING YIELDS RISE", move: "LONG", roi: "+60%", msg: "DA layer rewards increase." },
    { headline: "DYMENSION AIRDROPS", move: "LONG", roi: "+400%", msg: "RollApp ecosystem rewards early users." },
    { headline: "COSMOS HUB UPGRADE", move: "LONG", roi: "+30%", msg: "IBC improvements ship." },
    { headline: "OSMOSIS DEX SURGE", move: "LONG", roi: "+45%", msg: "Cosmos DeFi renaissance." },
    { headline: "NEUTRON SMART CONTRACTS", move: "LONG", roi: "+70%", msg: "CosmWasm gains traction." },
    { headline: "STRIDE LIQUID STAKING", move: "LONG", roi: "+55%", msg: "stATOM adoption grows." },
    { headline: "THORCHAIN STREAMING SWAPS", move: "LONG", roi: "+85%", msg: "Cross-chain DEX improves." },
    { headline: "MAYA PROTOCOL LAUNCH", move: "LONG", roi: "+110%", msg: "THORChain fork gains TVL." },
    { headline: "RADIX BABYLON UPGRADE", move: "LONG", roi: "+40%", msg: "Smart contracts finally live." },
    { headline: "KASPA HASHRATE ATH", move: "LONG", roi: "+200%", msg: "DAG PoW mining booms." },
    { headline: "ALEPH ZERO PRIVACY", move: "LONG", roi: "+65%", msg: "ZK meets substrate." },
    { headline: "ERGO MINING SPIKES", move: "LONG", roi: "+50%", msg: "GPU miners find home." },
    { headline: "FLUX DECENTRALIZED CLOUD", move: "LONG", roi: "+35%", msg: "Web3 infrastructure grows." },
    { headline: "AKASH GPU DEMAND SURGE", move: "LONG", roi: "+180%", msg: "AI needs compute. Akash delivers." },
    { headline: "RENDER NETWORK UPGRADE", move: "LONG", roi: "+90%", msg: "GPU rendering on Solana." },
    { headline: "IO.NET VALIDATION PASS", move: "LONG", roi: "+75%", msg: "Decentralized AI compute verified." },
    { headline: "BITTENSOR TAO STAKING", move: "LONG", roi: "+250%", msg: "AI meets crypto incentives." },
    { headline: "FET AI PARTNERSHIP", move: "LONG", roi: "+60%", msg: "Fetch.ai gains enterprise deals." },
    { headline: "OCEAN DATA MARKETPLACE", move: "LONG", roi: "+45%", msg: "Data monetization grows." },
    { headline: "SINGULARITYNET AGI MERGER", move: "LONG", roi: "+140%", msg: "AI token consolidation." },
    { headline: "WORLDCOIN ORBS EXPAND", move: "LONG", roi: "+30%", msg: "Eye scanning goes global." },
    { headline: "HELIUM 5G COVERAGE", move: "LONG", roi: "+55%", msg: "DePIN network grows." },
    { headline: "HIVEMAPPER MAPPING SURGE", move: "LONG", roi: "+70%", msg: "Decentralized Maps gain drivers." },
    { headline: "DIMO CAR DATA REWARDS", move: "LONG", roi: "+40%", msg: "Vehicle DePIN adoption." },
    { headline: "GEODNET RTK STATIONS", move: "LONG", roi: "+85%", msg: "Precision location data pays." }
];
