export const SCENARIOS = [
    { headline: "ELON TWEETED A DOG PIC", move: "LONG", roi: "+420%", msg: "The Dogefather has spoken. Your bags are mooning." },
    { headline: "SEC SUES DEFI PROTOCOL", move: "SHORT", roi: "+69%", msg: "Gary is angry again. Prices tank, but your short prints." },
    { headline: "DEV RUGGED THE LIQUIDITY", move: "SHORT", roi: "+900%", msg: "Classic move. You saw it coming and shorted the top." },
    { headline: "BLACKROCK ETF APPROVED", move: "LONG", roi: "+1000%", msg: "Institutional money is here. We are so back." },
    { headline: "EXCHANGE HALTS WITHDRAWALS", move: "SHORT", roi: "+100%", msg: "Not your keys, not your coins. Panic sellers filled your bags." },
    { headline: "INFLUENCER SHILLS 'GEM'", move: "SHORT", roi: "+50%", msg: "Exit liquidity secured. You dumped on them." },
    { headline: "FED PRINTS $1 TRILLION", move: "LONG", roi: "+200%", msg: "Money printer go BRRR. Assets fly up." },
    { headline: "SMART CONTRACT HACKED", move: "SHORT", roi: "+300%", msg: "Code is law? More like Code is Flawed." },
    { headline: "CHINA BANS BITCOIN (AGAIN)", move: "LONG", roi: "+150%", msg: "FUD is bullish. You bought the dip." },
    { headline: "VITALIK CLAPS HANDS", move: "LONG", roi: "+42%", msg: "The creator is happy. Gas fees drop, price goes up." },
    { headline: "STABLECOIN DE-PEGS TO $0.90", move: "LONG", roi: "+500%", msg: "You bought the fear. It re-pegged. Easy arbitrage." },
    { headline: "MEMECOIN LISTED ON BINANCE", move: "SHORT", roi: "+80%", msg: "Buy the rumor, sell the news. It crashed instantly." },
    { headline: "SBF ESCAPES PRISON", move: "SHORT", roi: "+666%", msg: "FTX 2.0 isn't happening. Market panic-dumps." },
    { headline: "USDT AUDIT FAILED", move: "SHORT", roi: "+99%", msg: "Tether truthers were right (for 5 mins)." },
    { headline: "NEW L2 AIRDROP ANNOUNCED", move: "LONG", roi: "+300%", msg: "Free money glitch. Farmers are eating good." },
    { headline: "NFT FLOOR PRICE CRASHES", move: "SHORT", roi: "+75%", msg: "JPEGs are illiquid. You shorted the collection." },
    { headline: "YOUTUBER MAKES 'SORRY' VIDEO", move: "SHORT", roi: "+120%", msg: "The scam unravels. You profited from the tears." },
    { headline: "MICHAEL SAYLOR BUYS MORE", move: "LONG", roi: "+10%", msg: "God candle incoming. There is no second best." },
    { headline: "SOLANA NETWORK RESTART", move: "SHORT", roi: "+40%", msg: "The blockchain is 'offline/online'. You hedged correctly." },
    { headline: "JIM CRAMER SAYS 'SELL'", move: "LONG", roi: "+888%", msg: "Inverse Cramer never fails. Historic pump." },
    { headline: "QUANTUM COMPUTER CRACKS SHA-256", move: "SHORT", roi: "+∞%", msg: "Game over. You shorted the apocalypse." },
    { headline: "A.I. TRADING BOT GOES ROGUE", move: "SHORT", roi: "+200%", msg: "SkyNet dumped the market." },
    { headline: "WIFE CHANGING MONEY", move: "LONG", roi: "+1000%", msg: "You bought a coin with a cat on it. It worked." },
    { headline: "DISCORD MOD DRAINS WALLET", move: "SHORT", roi: "+50%", msg: "Never click the link. You survived." },
    { headline: "GAS FEES HIT 5000 GWEI", move: "SHORT", roi: "+20%", msg: "Network unusable. Retail can't buy." },
    { headline: "ANANAS FUND DONATES 5000 BTC", move: "LONG", roi: "+30%", msg: "Whales are feeling generous." },
    { headline: "SATOSHI WALLET ACTIVATES", move: "SHORT", roi: "+5000%", msg: "The ancient one awakes. Terror in the streets." },
    { headline: "INTERNET SHUTDOWN", move: "SHORT", roi: "+100%", msg: "Can't trade if you can't connect." },
    { headline: "ALIENS BUY BITCOIN", move: "LONG", roi: "+9999%", msg: "Intergalactic adoption confirms the bull run." },
    { headline: "TAX SEASON STARTS", move: "SHORT", roi: "+15%", msg: "Everyone selling to pay Uncle Sam." },
    { headline: "ETHEREUM GOES PROOF-OF-STAKE", move: "LONG", roi: "+5%", msg: "Miners are mad, investors are glad." },
    { headline: "COINBASE SUPER BOWL AD", move: "SHORT", roi: "+40%", msg: "Top signal indicator. You sold." },
    { headline: "DO KWON FOUND ON MOON", move: "LONG", roi: "+100%", msg: "LUNA 3.0 pumps on the news." },
    { headline: "SEC APPROVES ETH ETF", move: "LONG", roi: "+250%", msg: "The flippening gets closer." },
    { headline: "NORTH KOREA HACKS BRIDGE", move: "SHORT", roi: "+150%", msg: "Lazarus Group strikes again." },
    { headline: "REDDIT API CHANGES", move: "SHORT", roi: "+10%", msg: "Moon farmers are on strike." },
    { headline: "NFT SOLD FOR $69 MILLION", move: "LONG", roi: "+500%", msg: "Art bubble is back." },
    { headline: "METAVERSE LAND SALE", move: "SHORT", roi: "+90%", msg: "Digital grass is useless. You flattened it." },
    { headline: "WEB3 PHONE RELEASED", move: "LONG", roi: "+60%", msg: "Airdrops included. Physical utility." },
    { headline: "BINANCE CEO RESIGNS", move: "SHORT", roi: "+44%", msg: "Funds are SAFU, but the price isn't." },
    { headline: "TWITTER REBRANDS TO X", move: "LONG", roi: "+69%", msg: "DOGE payments rumored. Speculation runs wild." },
    { headline: "GAMESTOP NFT MARKETPLACE", move: "SHORT", roi: "+80%", msg: "Too little, too late. Short squeeze failed." },
    { headline: "AMAZON ACCEPTS CRYPTO", move: "LONG", roi: "+300%", msg: "Jeff Bezos pumps your bags." },
    { headline: "LINK MARINES ASSEMBLE", move: "LONG", roi: "+100%", msg: "The oracle monopoly continues." },
    { headline: "LEDGER RECOVERS SEED", move: "SHORT", roi: "+200%", msg: "Trust broken. Hardware wallets tossed." },
    { headline: "BITCONNECT 2.0 LAUNCH", move: "SHORT", roi: "+1000%", msg: "Hey hey hey! No no no." },
    { headline: "PEPE FLIPS SHIBA", move: "LONG", roi: "+420%", msg: "The frog creates a new paradigm." },
    { headline: "GOLDMAN SACHS SHORT", move: "LONG", roi: "+50%", msg: "Bankers are wrong. Again." },
    { headline: "CRYPTO BAN IN INDIA", move: "SHORT", roi: "+30%", msg: "Another ban? Another dip to buy later." },
    { headline: "ETHEREUM KILLER LAUNCHED", move: "SHORT", roi: "+95%", msg: "It died in 2 months. Expected." },
    { headline: "LOGAN PAUL PROJECT", move: "SHORT", roi: "+100%", msg: "Never trust a YouTuber. Refund unclear." },
    { headline: "APPLE DELISTS METAMASK", move: "SHORT", roi: "+40%", msg: "Walled garden strikes back." },
    { headline: "MICROSTRATEGY MARGIN CALL", move: "SHORT", roi: "+200%", msg: "Staylor got liquidated? No way." },
    { headline: "BTC DOMINANCE HITS 70%", move: "SHORT", roi: "+20%", msg: "Altcoins are bleeding out." },
    { headline: "ALTSEASON HAS BEGUN", move: "LONG", roi: "+1000%", msg: "Everything is going up. Even the trash." },
    { headline: "HACKER RETURNS FUNDS", move: "LONG", roi: "+50%", msg: "White hat saviour? Or just scared?" },
    { headline: "FED PIVOT CONFIRMED", move: "LONG", roi: "+400%", msg: "Rates are cut. Risk-on assets explode." }
];
